frontend/package-lock.json, frontend/package.json, frontend/src/App.css, frontend/src/App.jsx, frontend/src/Reset.css, frontend/src/components/NavBar.jsx, frontend/src/main.jsx, frontend/src/pages/Home.jsx, frontend/src/pages/Login.jsx
Added pages directory in frontend, created Home and Login page files, created NavBar component, added CSS styling to NavBar, added CSS Reset file, added react-router-dom
The CSS styling is open to modification, I just threw a little something together to get the idea going.
=> KAN-1/Navbar-Components -> main

backend/app.py
Added a test line to print a line of data from the database to confirm the connection is working. This test line will be deleted once we can all confirm this is working on our machines.
=> Uncomment lines to enable supabase connection

backend/app.py, frontend/src/App.jsx, frontend/src/components/DeleteTripButton.jsx, frontend/src/components/EditTripButton.jsx, frontend/src/components/TripTile.jsx, frontend/src/css/MyTrips.css, frontend/src/css/TripTile.css, frontend/src/pages/MyTrips.jsx
Created the Delete Trips Button that allows for a user to delete a specific trip; backed functionality has been implemented.
Created the Edit Trip Button that redirects users to an EditTrips page. 
https://github.com/user-attachments/assets/b9913c99-9b11-41e7-9619-200b2d25b929
=> Kan17: Delete and Edit buttons for Trips

backend/app.py, frontend/src/App.jsx, frontend/src/components/TripTile.jsx, frontend/src/css/MyTrips.css, frontend/src/css/TripTile.css, frontend/src/pages/MyTrips.jsx
Create React components and add functionality to fetch a user’s list of trips and place them on clickable tiles.
https://github.com/user-attachments/assets/6650907d-b981-4288-8aba-08f2d7cd5a4e
=> Kan20: Trip Tiles 

frontend/src/components/SearchBar.jsx, frontend/src/css/SearchBar.css, frontend/src/pages/Home.jsx
- Added a new `SearchBar` component to enhance user search functionality on the Home page.
- Updated the `Home` page to include the `SearchBar`, allowing users to search by location and keywords.
Please test the new search functionality on various devices to ensure it works smoothly:
- Verify that the `SearchBar` captures user input accurately.
1. Pull this branch.
2. Run the application locally using `npm start` or `npm run dev`.
3. Navigate to the Home page.
4. Enter a location and keywords in the `SearchBar`.
5. Click the search button and verify that it captures the input correctly.
The addition of the `SearchBar` component enhances the user experience by allowing users to search for specific locations and keywords, making the application more interactive and functional. This is a …
=> Add SearchBar component and update Home page

backend/app.py, frontend/src/App.jsx, frontend/src/components/DeleteTripButton.jsx, frontend/src/components/Description.jsx, frontend/src/components/EditTripButton.jsx, frontend/src/components/SaveChanges.jsx, frontend/src/components/TripTile.jsx, frontend/src/css/MyTrips.css, frontend/src/css/TripTile.css, frontend/src/pages/EditTrip.jsx, frontend/src/pages/MyTrips.jsx
Created the EditTrips Button 
Created EditTrip Page 
Implemented Database functionality
https://github.com/user-attachments/assets/ddf251ad-c0d7-4a4f-b14e-4e76dcba30f6
=> Kan 19: edit button and page

backend/app.py, frontend/src/components/Description.jsx, frontend/src/components/EditTripButton.jsx, frontend/src/components/SaveChanges.jsx, frontend/src/components/SaveTripButton.jsx, frontend/src/pages/CreateTrip.jsx, frontend/src/pages/EditTrip.jsx
Created the SaveTripButton that saves newly created trips
Created the CreateTrip Page where users can create a new trip
Implemented backend functionality for saving a trip in a database
https://github.com/user-attachments/assets/16293e06-d907-4d85-ab8e-714dd6ededd8
=> Kan 18: SaveTripButton, CreateTrip Page,  and backend functionality

backend/app.py, frontend/src/components/Description.jsx, frontend/src/components/EditTripButton.jsx, frontend/src/components/SaveChanges.jsx, frontend/src/components/SaveTripButton.jsx, frontend/src/components/TripTile.jsx, frontend/src/pages/CreateTrip.jsx, frontend/src/pages/EditTrip.jsx, frontend/src/pages/IndividualTrip.jsx
You can view an individual trip information
https://github.com/user-attachments/assets/a1178ee8-e96d-4fd3-b19f-7890bf5ddc7f
=> Kan 22: Displays Trip Information

backend/.gitignore, backend/app.py, backend/requirements.txt, backend/user_controller.py, frontend/.gitignore, frontend/src/pages/CreateAccount.jsx
Added backend route for account creation and updated frontend account creation page to utilize the backend to create an account in the database.
=> Kan 5/backend account creation

backend/user_controller.py, frontend/src/components/NavBar.jsx, frontend/src/pages/Login.jsx
Added login functionality and ran user_controller.py through a linter.
=> Kan 6/backend login

backend/app.py, frontend/src/App.jsx, frontend/src/components/DeleteExperienceButton.jsx, frontend/src/components/EditExperienceButton.jsx, frontend/src/components/ExpSaveChanges.jsx, frontend/src/components/ExperienceTile.jsx, frontend/src/components/Keywords.jsx, frontend/src/pages/CreateExperience.jsx, frontend/src/pages/EditExperience.jsx, frontend/src/pages/IndividualExperience.jsx, frontend/src/pages/MyExperiences.jsx
https://github.com/user-attachments/assets/62b2e9ca-27ac-4d58-ad71-5fba7f8184f5
Updates to the experience management features. The following changes have been implemented:
1. My Experiences Page:
Fetched experiences from the backend and displayed them in Tiles 
Each experience tile includes:
Experience Title
Edit Button: Navigates to the Edit Experience page for modifying details.
Delete Button: Allows users to remove the experience from the backend.
2. Edit Experience Page
Users can update fields such as experience name, description, address, latitude, longitude, photo URL, and rating.
(TODO: need to implement keywords updating) 
3. Individual Experience Page
Includes Edit button 
4. Backend Integration 
- Delete functionality for an experience
- Update functionality for an experience 
- …
=>  Experience Management Features Implementation

backend/trip_controller.py, frontend/src/App.jsx, frontend/src/components/DeleteTripButton.jsx, frontend/src/components/RemoveTripExperienceButton.jsx, frontend/src/components/SaveChanges.jsx, frontend/src/components/SaveTripButton.jsx, frontend/src/components/TripTile.jsx, frontend/src/pages/IndividualTrip.jsx, frontend/src/pages/MyTrips.jsx
Pair programmed w/Dion to add authorization to all routes associated with backend calls for trips.
=> Add authorization to all trip routes

backend/experience_controller.py, frontend/src/App.jsx, frontend/src/components/DeleteExperienceButton.jsx, frontend/src/components/ExpSaveChanges.jsx, frontend/src/components/ExperienceTile.jsx, frontend/src/css/ExperienceTile.css, frontend/src/pages/CreateExperience.jsx, frontend/src/pages/IndividualExperience.jsx, frontend/src/pages/MyExperiences.jsx
Followed Dion and Tysons changes to Trips and applied same method to the Experiences routes and associated code
=> Added Authorization to all Experience Routes 

frontend/src/pages/CreateAccount.jsx
Make form validation instant on the create account page rather than only after trying to submit
=> KAN-96/Create_Account_Instant_Validation

frontend/src/css/IndividualExperience.css, frontend/src/pages/CreateExperience.jsx, frontend/src/pages/EditExperience.jsx, frontend/src/pages/IndividualExperience.jsx
1. Fixed routing to myExperiences page after new Experience Saved Successfully 
2. Added "Cancel" button while in "Edit" Mode for an Experience, that routes back to the Individual Experience page 
3. Styling for Individual Experience 
https://github.com/user-attachments/assets/9d762267-41ad-4750-95dc-9fbad68d8381
=> Changed Styling for Individual experience Page

backend/experience_controller.py, frontend/src/components/AddExperienceToTripButton.jsx, frontend/src/components/ExperienceTile.jsx
Implemented backend and frontend functionality for adding a Trip to an Experience Button 
https://github.com/user-attachments/assets/9f0d0be8-72b4-4b88-8247-1a64333945f7
=> Add Experience to Trip Button 

backend/search_controller.py, frontend/src/components/SearchBar.jsx
- Lowercased keywords in `SearchBar` to ensure consistent, case-insensitive filtering on the backend.
- Optimized ratings calculation in the backend using a list comprehension for cleaner and more efficient code.
Please test the following:
- Verify that the search functionality accurately handles case-insensitive keywords and returns correct results.
- Ensure that the ratings calculation is accurate and displays properly on the front end.
=> Improve Search Functionality and Optimize Backend Ratings Calculation

frontend/src/css/NavBar.css
Reduced the size of the logo and the navbar buttons to avoid the issue of the navbar overflowing from the page on smaller screens.
=> Adjust sizing of navbar elements

frontend/package-lock.json, frontend/package.json, frontend/src/App.jsx, frontend/src/components/GeolocationInput.jsx, frontend/src/pages/CreateExperience.jsx
- **Added `@react-google-maps/api` library** to support autocomplete functionality.
- **Integrated Autocomplete** into the `CreateExperience` component for location input.
- **Updated `App.jsx`:**
- Included `LoadScript` wrapper for loading the Google Maps JavaScript API.
- Added `places` library for autocomplete functionality.
- **`CreateExperience.jsx`:**
- Added Google Autocomplete for address input.
- Implemented logic to auto-populate latitude and longitude fields based on the selected address.
- **`GeolocationInput.jsx`:**
- Simplified to make geolocation fields read-only, reflecting auto-populated values from the selected location.
- **Updated `package.json`** to include the `@react-google-maps/api` dependency.
- **Enhanced User Experience:** Provides users with a convenient and …
=> Google Places Autocomplete Integration

frontend/src/components/AddExperienceToTripButton.jsx, frontend/src/css/AddToExperienceButton.css, frontend/src/css/ExperienceTile.css, frontend/src/css/FeedPage.css, frontend/src/css/IndividualExperience.css, frontend/src/css/MyExperiences.css, frontend/src/pages/FeedPage.jsx, frontend/src/pages/IndividualExperience.jsx, frontend/src/pages/MyExperiences.jsx
https://github.com/user-attachments/assets/46f734a7-51c5-40b5-a6f5-2d4eeba83836
=> Experience Tile and Individual Experience CSS Changes 

frontend/src/components/ButtonLink.jsx, frontend/src/components/ExperienceTile.jsx, frontend/src/components/TripExperienceTile.jsx, frontend/src/pages/IndividualExperience.jsx, frontend/src/pages/IndividualTrip.jsx
Fix back button routing to properly route to previous page
=> KAN-113/back_button_routing

frontend/src/pages/IndividualExperience.jsx
Added Created time to experience page
=> Added created time to experience

frontend/src/components/AddExperienceToTripButton.jsx, frontend/src/components/ButtonLink.jsx, frontend/src/components/EditExperienceButton.jsx, frontend/src/components/ExpSaveChanges.jsx, frontend/src/components/ExperienceTile.jsx, frontend/src/components/TripTile.jsx, frontend/src/pages/EditExperience.jsx, frontend/src/pages/IndividualExperience.jsx
Fixed all pathing bugs associated with the cancel and back buttons (any button that utilizes the ButtonLink.jsx component).
I also fixed the issue associated with adding an experience to a trip via the individual experience page.
=> Fix pathing bugs

frontend/src/components/TripExperienceTile.jsx, frontend/src/pages/FeedPage.jsx, frontend/src/pages/IndividualTrip.jsx
- **Updated `TripExperienceTile.jsx`:**
- Imported the existing `AddExperienceToTripButton`.
- Added conditional rendering for the button using a new `showAddButton` prop.
- **Modified `IndividualTrip.jsx`:**
- Passed `showAddButton={false}` to hide the button where it is not needed.
=> Add Conditional AddExperienceToTripButton to TripExperienceTile and Update IndividualTrip Logic

frontend/src/css/MyExperiences.css, frontend/src/pages/MyExperiences.jsx
Moved + Experience button to the bottom of MyExperiences page
=> changed styling for MyExperience page to match MyTrips

frontend/src/components/TripTile.jsx, frontend/src/css/MyTrips.css, frontend/src/css/TripTile.css, frontend/src/pages/MyTrips.jsx
- Adjusted the layout of the trips container for improved alignment and spacing.
- Enhanced hover effects for a visually appealing user experience.
- Made the entire trip tile clickable while retaining button-specific functionality.
- Centered the trip title within the tile for a clean and consistent appearance.
- Balanced spacing between the title and action buttons (Edit and Delete).
---
These changes ensure a polished and intuitive user interface for the trips page and trip tiles.
=> Update Trips Page and Tile Styling

frontend/src/components/DeleteExperienceButton.jsx, frontend/src/pages/IndividualExperience.jsx
1. Fixed routing issue when in inidividual experience page, then clicking on delete, then Cancel button 
2. Still need to fix routing issue when in inidividual experience page, then clicking on delete, then Okay button
=> Fixing Routing Bugs in individual expereince DELETE button  
